name: Release
on:
  repository_dispatch:
    types: [release]

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: yarn install
      - name: Create .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      - name: Set git username
        run: git config user.name "github-actions"
      - name: Fetch tags
        run: git fetch --prune --unshallow
      - name: Release packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
