name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test --coverage
  package-build:
    name: Package build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: yarn install
      - name: Bootstrap packages
        run: ./node_modules/.bin/lerna bootstrap
  storybook-build:
    name: Storybook build test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: yarn install
      - name: Bootstrap packages
        run: ./node_modules/.bin/lerna bootstrap
      - name: Build storybook
        run: yarn build-storybook
